version: '3'

services:

  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - s3
    image: apache/james:distributed-3.7.3
    container_name: james
    hostname: james.local
    volumes:
      - "F:/data/docker/james/conf/keystore:/root/conf/keystore"
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node

  cassandra:
    image: cassandra:3.11.10
    ports:
      - "9042:9042"
    volumes:
      - F:/data/docker/cassandra:/var/lib/cassandra
      - F:/data/docker/cassandra/logs:/var/log/cassandra
    environment:
      - logging.level.root=error

  tika:
    image: apache/tika:1.28.2
  rabbitmq:
    image: rabbitmq:3.9.18-management
    ports:
      - "5672:5672"
      - "15672:15672"

  s3:
    image: zenko/cloudserver:8.2.6
    container_name: s3.docker.test
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=secretKey1
      - S3BACKEND=mem
      - LOG_LEVEL=trace
      - REMOTE_MANAGEMENT_DISABLE=1
